CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100),
  "email" varchar(100) UNIQUE,
  "senha_hash" varchar(255),
  "data_nascimento" date,
  "genero" "enum(Masculino,Feminino,Outro,Prefiro não dizer)",
  "altura" decimal(5,2),
  "peso" decimal(5,2),
  "criado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "hidratacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "quantidade_ml" int,
  "registrado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "atividades_fisicas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "tipo" varchar(100),
  "duracao_min" int,
  "calorias_queimadas" int,
  "registrado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "alimentacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "descricao" varchar(255),
  "calorias" int,
  "registrado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "humor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sentimento_id" int,
  "usuario_id" int,
  "atividade_id" int,
  "alimentacao_id" int,
  "observacao" text,
  "registrado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "alertas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "mensagem" varchar(255),
  "tipo" enum(Água,Exercício,Alimentação,Outro),
  "horario" time,
  "ativo" boolean DEFAULT (true)
);

CREATE TABLE "conteudos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar(255),
  "tipo" enum(Artigo,Vídeo),
  "url" text,
  "descricao" text,
  "criado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "interacoes_conteudo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "conteudo_id" int,
  "tipo" enum(Visualizado,Curtido),
  "registrado_em" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "sentimentos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "humor" varchar(50),
  "categoria" varchar(50)
);

ALTER TABLE "hidratacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "atividades_fisicas" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "alimentacao" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "humor" ADD FOREIGN KEY ("sentimento_id") REFERENCES "sentimentos" ("id");

ALTER TABLE "humor" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "humor" ADD FOREIGN KEY ("atividade_id") REFERENCES "atividades_fisicas" ("id");

ALTER TABLE "humor" ADD FOREIGN KEY ("alimentacao_id") REFERENCES "alimentacao" ("id");

ALTER TABLE "alertas" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "interacoes_conteudo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "interacoes_conteudo" ADD FOREIGN KEY ("conteudo_id") REFERENCES "conteudos" ("id");
